- alias: 'Lollo Away'
  trigger:
  - platform: state
    entity_id: device_tracker.lollo
    from: home
    to: not_home
    
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.charlieovn
        temperature: 22
        operation_mode: Heat
    - service: climate.charlieovn
      data:
        entity_id: climate.charlieovn
        temperature: 17
        operation_mode: Heat
    - service: light.turn_off
      entity_id: light.room_lollo