- alias: 'Ninni Away'
  trigger:
  - platform: state
    entity_id: device_tracker.ninni
    from: home
    to: not_home
    
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.ninniovn
        temperature: 22
        operation_mode: Heat
    - service: climate.ninniovn
      data:
        entity_id: climate.ninniovn
        temperature: 17
        operation_mode: Heat
    - service: light.turn_off
      entity_id: light.room_ninni