- alias: 'Ninni_hjem'
  trigger:
    - platform: state
      entity_id: device_tracker.ninni
      from: 'not_home'
      to: 'home'
# I owe https://github.com/Danielhiversen/home-assistant_config/blob/master/automation/soverom.yaml a coffe
  action:
    - service: media_player.turn_on
      entity_id: media_player.stue3
    - service: media_player.volume_set
      data:
        entity_id: media_player.stue3
        volume_level: 0.55
    - service: tts.google_say
      entity_id: media_player.stue3
      data_template:
        message: ' Welcome Home cutiepie'
    - service: climate.set_temperature
      data:
        entity_id: climate.ninniovn
        temperature: 17
        operation_mode: Heat
    - service: climate.ninniovn
      data:
        entity_id: climate.ninniovn
        temperature: 22
        operation_mode: Heat
    - service: light.turn_on
      entity_id: light.room_ninni